baseURL = "https://orangeoi.qzz.io/"
title = "Milk_Dragon's blog"
theme = "stack"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
hasCJKLanguage = true

[permalinks]
    posts = ":year/:month/:day/:slug/"

[params]
    mainSections = ["posts"]
    rssFullContent = true
    favicon = "/img/avatar.jpg"

    [params.sidebar]
        subtitle = "我是奶龙"
        avatar = "/img/avatar.jpg"

    [params.article]
        math = true
        readingTime = true

    [params.footer]
        since = 2026

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions.passthrough]
            enable = true
            [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)']]
    [markup.highlight]
        style = "dracula"
        lineNumbers = true
