baseURL = "https://orangeoi.qzz.io/"
title = "Milk_Dragon's blog"
theme = "stack"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
hasCJKLanguage = true

[permalinks]
    posts = ":year/:month/:day/:slug/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions.passthrough]
            enable = true
            [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)']]
    [markup.highlight]
        style = "dracula"
        lineNumbers = true
